### ISSUE TITLE
.htaccess should block everything by default and only allow through requests to "the right things"

### ISSUE THREAD

**Issue by obra** [idno/Known#10]
should I be able to request arbitrary .php files under Idno*, external or templates?
##

**Comment by physcocode** [comment]
this has been fixed i guess

**Comment by kylewm** [comment]
It very hasn't ;) e.g., you can hit `/IdnoPlugins/Status/Pages/Edit.php` on any site, and it will execute it (fortunately it just causes an error). But ideally that should 404 or 403

**Comment by kylewm** [comment]
>  I've always tried hard to not mix assets and executed/intepreted content in the same directory structure

So it turns out to be pretty trivial to move index.php, external/, gfx/, js/, and css/ to a folder (I called it `public/`) and make that the wwwroot. 

The problem is that then there is no way for plugins or themes to include custom static resources -- since they all live outside of the wwwroot, and I am drawing a blank on how to manage this. Any ideas?

**Comment by kylewm** [comment]
There should probably be points awarded for fixing issues with the lowest number. :+1:

**Comment by benwerd** [comment]
Sadly reopening this because the .htaccess blocked access to /warmup. Should be able to recommit soon, but pushing out an emergency new release.

**Comment by kylewm** [comment]
Might just need to substitute `.*` for `*` in `<Files ~ "warmup\/*\.php">`

**Comment by benwerd** [comment]
I tried that - not working at this end. It'll be something equally small though ;)

**Comment by mapkyca** [comment]
Pretty sure this is handled by the various .htaccess deny alls in the appropriate dirs, but there's likely need for similar nginx configs
