### ISSUE TITLE
MySQL privacy incantation

### ISSUE THREAD

**Issue by markwaters** [idno/Known#1006]
Now that 'Per-post privacy' is available I would like to switch my site from Private to Public.
Is it possible to use a MySQL incantation to mass switch all my posts from Public to Private ?
If so can someone suggest it ?
Thanks.

**Comment by benwerd** [comment]
It unfortunately isn't easy, because of our schema. You could make the whole site private, of course.

If there WAS a way, and I'm not at all suggesting you should do this, and you should definitely back up your whole database first, and this is entirely at your own risk, you could:

1. Do a search and replace on 'PUBLIC' in the 'content' field of the entities table, for entities where entity_subtype was not Idno\Entities\User, replacing it with your user URI
2. Find all non-user entity URLs and then update metadata where 'name' = access and 'value' = 'PUBLIC', replacing it with your user URI

But it's fiddly and dangerous. Probably easier to write a script. This is a feature that, eg, LiveJournal has always provided, and it makes some sense for us to provide it, too.

**Comment by markwaters** [comment]
Thanks @benwerd , I have got part 1 sorted , will change it to a script and incorporate part 2.

**Comment by markwaters** [comment]
Hhmm , the contents field shows as a 'blob' and is not editable in phpmyadmin so I am stuck.
I admit defeat and will have to wait for the feature to be implemented or go through each post manually.

**Comment by danito** [comment]
Hi,
you can change the blob fields to longtext, that what I did when I had to
change the url of my userid for each entity after I changed the url for my
site.

On Thu, Aug 13, 2015 at 9:26 AM, Mark Waters <notifications@github.com>
wrote:

> Hhmm , the contents field shows as a 'blob' and is not editable in
> phpmyadmin so I am stuck.
> I admit defeat and will have to wait for the feature to be implemented or
> go through each post manually.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/1006#issuecomment-130564141>.
>



-- 
Daniel Nix
