### ISSUE TITLE
replies from Twitter do not contain long url

### ISSUE THREAD

**Issue by danito** [idno/Known#1060]
I don't know if this is a brid.gy or a Known (sic) problem, but when getting a reply from Twitter, only the truncated text if displayed and not the actual link. Example : https://nxd4n.nixekinder.be/2015/diplix-gibts-eigtl-auch-ein-rss-fr-all-bin-da
Brid.gy sents this https://brid-gy.appspot.com/comment/twitter/nxD4n/645988180144050178/645988847017402368

**Comment by kylewm** [comment]
For better or worse, this is the expected behavior for both Known and Bridgy.

Known strips out HTML in incoming comments, so you are getting the plain-text version of the mention from Bridgy.

and Bridgy uses the display_url that Twitter gives it (which is ellipsized):

```
    "urls": [
      {
        "url": "http://t.co/wVlBTPY3yZ",
        "expanded_url": "http://wirres.net/article/rss/full/0/10/",
        "display_url": "wirres.net/article/rss/fu…",
        "indices": [
          7,
          29
        ]
      }
```

**Comment by danito** [comment]
Where is this parsed? Can I hack it by str_replace($display_url,$display_url,$comment) so that links are not lost if the original tweet is deleted?

**Comment by kylewm** [comment]
It looks like webmention content is parsed and tags are stripped right about here:

https://github.com/idno/Known/blob/815164a0ac14a571b8b5c1ababa99edeec5a701a/Idno/Common/Entity.php#L1745

**Comment by kylewm** [comment]
Hey @snarfed, has the ellipsized twitter display_url been discussed previously in Bridgy? Twitter seems to be a bit aggressive in cutting the URL short...

**Comment by benwerd** [comment]
It would be way smarter of us to either:

1. Replace the link with the full href contents, in the case when the link text is also a URL or URL fragment

Or: 

2. Not strip HTML from incoming comments, but sanitize them instead (riskier)

Any thoughts in either direction?

**Comment by snarfed** [comment]
interesting! i'm sure this has happened lots of times before, but i think this is the first time i've heard of it myself, which probably means people don't notice or care that often. (no guarantees though; i have a horrible memory. :P)

@benwerd either of those options sounds good to me! i lightly vote for #2, since i often link actual text in replies, but i don't feel strongly.

straw man alternative: on the bridgy side, we could theoretically add a hidden p-content with plain text and full length URLs. all users would then need modern mf2 parsers to handle that, if it's even legit at all, and they'd need to choose between e- and p-content intelligently. kinda big asks.

**Comment by mapkyca** [comment]
This (https://github.com/mapkyca/KnownHTMLPurifier) might be handy for 2...

**Comment by benwerd** [comment]
Alright, sold. Let's purify some HTML.
