### ISSUE TITLE
Convert Known dependencies to optionally use Composer

### ISSUE THREAD

**Issue by benwerd** [idno/Known#1064]
Because it's 2015.
##

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/1064" class="u-in-reply-to"></a>Y'mean instead of using github modules or including native?

Not entirely sure how you could do it optionally and not introduce an extra step, and if you do that you might as well use native modules rather than make everyone wget rootkit.php ...

**Comment by kylewm** [comment]
I'd still love to see this, and before 1.0 is a good time IMHO. 

Rather than making it optional, I'd vote to adopt it and remove Symfony's UniversalClassLoader altogether. You'd still package the `vendor/` folder for releases, so people downloading a zip wouldn't need to install or use composer. But it would add an extra step for folks checking out from git.

In addition to all the nice stuff Composer gives you, I think it would remove a barrier to contribution... 

I started messing with it here, and it was surprisingly easy to get up and running:

  https://github.com/idno/Known/compare/master...kylewm:composer

Other than AutoP.php, there were packages for everything I looked for, and I think I more or less found the correct versions.

**Comment by benwerd** [comment]
Composer is the standard way to include PHP modules in a modern project, so, okay: let's take another look. :)

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/1064#issuecomment-177046710" class="u-in-reply-to"></a>My €0.02 is that including dependencies in the binary are preferable as it gives you everything ready to go and there's less chance of tampering. 

Git submodules are next preferable because since it's a tool you're likely to have installed and you can peg modules to a known release.

Composer in my view is convenient (although not that convenient because you still have to install composer), but it scares the shit out of me because literally the first thing they tell you to do is "Please download and run this unverified script directly off the internet, but trust us it'll be *fiiiiiiine*".

Or as I said in my previous comment, "wget rootkit.php"

**Comment by physcocode** [comment]
+1 to @mapkyca  composer is always the last choice for me including binary in the dependencies is cool as it removes the extra step of composer update .I am not totally against composer but i like the way know is currently loaded independent of a any extra step that composer would add

**Comment by kylewm** [comment]
@mapkyca are you referring specifically to `curl getcomposer... | php`, or are you skeeved by installing dependencies from packagist in general? I know [MavenCentral is/was a huge security hole](http://blog.ontoillogical.com/blog/2014/07/28/how-to-take-over-any-java-developer/) in the Java world.

From a security standpoint, I'd argue the gains far exceed the cost. The current situation is we're running a bunch of unversioned, outdated libraries on publicly accessible web servers. Maybe there have been security fixes to Symfony since 2013 when 2.3.0 was released.

As far as adding an extra step, yeah that's a judgement call. I think long term it'd be nice to add an alpha/nightly release channel that would package up all the dependencies (and some set of non-core plugins?) for people who just want the latest version of the software. Then the git version would really just be for developers who I think would be accustomed to using dependency management.

**Comment by aaronpk** [comment]
+1 for using composer to manage dependencies. It provides a quick way to get security updates from libraries you're using.

+1 for making a complete package available for download that includes the vendor folder, so someone installing it can just drop the files in and go, and not worry about composer.

**Comment by physcocode** [comment]
@aaronpk  @benwerd lets get done away with both
* An optional composer install
* And an non-composer direct alternative

I am a bit against depending completely on composer . whats your suggestion ?

**Comment by benwerd** [comment]
I'm inclined to create a fully-installable bundle (which we always need to do anyway) in addition to using composer. Composer is fully-supported by most hosts, so it also comes with, eg, AWS integration for free.

**Comment by mapkyca** [comment]
@kylewm Thats a valid point, aye. 

I guess I just get twitchy whenever I see anything like the composer installer instructions - if I can get you to cut and paste a command onto your terminal, I can root your system. Zonealarm/windows vista boxen taught a generation of users to just click Ok on dialog boxes, now we're teaching a generation of coders to blindly run random scripts is an ok thing to do.

Blame my fuddy duddy infosec background.

**Comment by kylewm** [comment]
So full disclosure: I'm slightly ambivalent. A few years ago I converted an older project at work to use Maven and later Gradle, and I think people were always kind of irritated at me that they had to use this arcane thing instead of just dropping jars into Eclipse like they always had. In the end I thought dependency management was objectively better than what we were doing before but not worth the pain it caused everyone who wasn't me. (See also: converting projects from Subversion to Mercurial)

Gratefully Composer is not Maven, but I'm a little gun-shy still... Is this something you want to make an executive decision on @benwerd, or on the other end of the spectrum open up to the mailing list?

**Comment by physcocode** [comment]
we should actually include composer (it's so 2016) but also let the simple way of known is there any middle way out?

**Comment by kylewm** [comment]
@physocode like Ben said [above](https://github.com/idno/Known/issues/1064#issuecomment-177328678), the release .zip files would (continue to) include all dependencies. Only developers and people wanting bleeding edge code from git would need to worry about Composer. Does that satisfy the non-Composer-alternative you are suggesting?

**Comment by physcocode** [comment]
@kylewm @benwerd this sounds satisfying and balanced +1 for this solution

**Comment by aaronpk** [comment]
Yes I was trying to say that there should always be a release version available that works without someone using or knowing about composer. Ultimately all composer does is put things in the "vendor" folder and set up autoload rules. After you run `composer install` the result is a pile of PHP that runs without any further interaction with composer.

**Comment by physcocode** [comment]
I suggest merging the composer request this is pretty cool and convenient (well i did a petty more research on composer and i like it).  We can also have the known official package on Packagist @benwerd some lights please :)

**Comment by kylewm** [comment]
I'm discovering a really annoying issue with using Composer. I have two plugins:

- Reactions
  - requires mf2/shim
    - requires mf2/mf2 (`IdnoPlugins/Reactions/vendor/mf2/mf2/Mf2/Parser.php`)
- IndieSyndicate
  - requires indieauth/client
     - requires mf2/mf2 (`IdnoPlugins/IndieSyndicate/vendor/mf2/mf2/Mf2/Parser.php`)

when composer attempts to `require` the second copy of Parser.php, it dies with a fatal "Cannot redeclare class Mf2\Parser"

Looks like this issue has come up with [Craft](https://experiencehq.net/blog/craft-plugin-composer-dependency-conflicts#fnref:package-versions) and [Wordpress](http://wptavern.com/a-narrative-of-using-composer-in-a-wordpress-plugin). 

There are a couple of issues:
* two plugins use different versions of a dependency -- you can't predict which version will load, so one plugin will (silently) have the wrong version.
* two plugins use the same dependency and it is defined with `"autoload": {"file": ...}` -- php will have a fatal error when it tries to require the second copy of the file.

I think this is a blocker on adopting Composer. `UniversalClassLoader` has a lot of the same issues, but at least with it, we are in charge of adding dependencies and can do some programmatic checks.

**Comment by mapkyca** [comment]
This is an old ticket, and personally I'm in no hurry to add extra complexity, my personal feelings about composer notwithstanding.

Going to call time on this for now, pull requests welcome if this is really a big deal for folk.
