### ISSUE TITLE
Move all static, publicly accessible files to their own directory tree

### ISSUE THREAD

**Issue by benwerd** [idno/Known#11]
All static Javascript, CSS and image files should live in their own directory structure, which should be configurable to live at a user-definable path.
##

**Comment by benwerd** [comment]
Bumping this as a thing to think about again.

**Comment by physcocode** [comment]
basically the bootstrap should leave the external and make way to css . Everything should be on a single place . And these should be rendered via tempting engine rather than directly directly calling from path this would help in bringing CDN support in future . I use this convention in my projects .

**Comment by mapkyca** [comment]
Closing, since I believe this is done...
