### ISSUE TITLE
order comments by mf2 dt-published or dt-updated

### ISSUE THREAD

**Issue by snarfed** [idno/Known#1104]
...if available. looks like right now they're ordered by webmention receipt time.

[requested here](https://github.com/snarfed/bridgy/issues/562#issuecomment-160182361) by @beck24. the use case is bridgy (etc), since it polls and so it often sends multiple comments in batches.

example: these two comments on http://known.mattbeckett.me/2015/buy-nothing-this-black-friday :
* _How much was it Matt?_ https://brid-gy.appspot.com/comment/facebook/948590525171368/1070591592971260/1070590272971392_1070656022964817
* _$3500_ https://brid-gy.appspot.com/comment/facebook/948590525171368/1070591592971260/1070590272971392_1070656466298106

happy thanksgiving btw!

**Comment by snarfed** [comment]
:tada: :pray:

**Comment by jaduncan** [comment]
I'm currently getting incorrectly ordered comments on FB and Twitter comments sent from bridgy. I'm running 0.9.2 as provided by Reclaim Hosting (stock, I would think) and the order is broken in that, while comments from different bridgy pushes are ordered correctly, if bridgy is picking up multiple comments in one check (let's say that 10 have been added since bridgy last scanned FB) then the order within those 10 comments is random.
