### ISSUE TITLE
Most POSSE broken

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#1132]
I've not had a chance to debug, but it seems that all POSSE (facebook/twitter etc) is broken in the latest build, from my site at least.

Will investigate when I'm back at my computer.

**Comment by mapkyca** [comment]
It *looks* like there's an object/session issue going on, as the user object seems to have forgot all account information.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/1132" class="u-in-reply-to"></a>Reconnecting the channel doesn't seem to work...

**Comment by mapkyca** [comment]
Github channel still functions, just seems to be twitter and facebook.

**Comment by kylewm** [comment]
Darn, almost certainly this is caused by https://github.com/idno/Known/pull/1125 ... Thank you for the catch

I suspect my changes to the Twitter/Facebook plugins were less backward compatible than I was thinking. I need to go back in and try to make sure older plugins work with the new auth order, and also that newest changes to Twitter/Facebook plugins work with the old auth order.

Do yo have the absolute latest repository versions of everything? I'm hoping you either have the newest Known and slightly older Twitter/Facebook plugins or vice versa

**Comment by benwerd** [comment]
NB: the plugins already contain breaking changes with the previous version
of Known. The only really important thing is that they work with the latest
code base.

I'll be able to take a look a little later today too.

On Monday, January 11, 2016, Marcus Povey <notifications@github.com> wrote:

> Github channel still functions, just seems to be twitter and facebook.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/1132#issuecomment-170511630>.
>


-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by kylewm** [comment]
hmm, @benwerd in that case do you think I should update the other syndication plugins, or would it be better to change the core code so that it does user auth before *and* after the plugins are created? (the latter solution would work technically but would be a performance hit for every authed request)

**Comment by mapkyca** [comment]
Pretty sure I'm running the latest twitter/facebook plugins, but I'll double check when I get home...

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/1132" class="u-in-reply-to"></a>Ok, it looks like there was an old plugin code there somewhere, so panic over.

Looks like a conflict blocked updates somewhere.

**Comment by benwerd** [comment]
@kylewm Sorry for late reply - I think we should just update the plugins. I see you've sent some pull requests, which I really appreciate!

**Comment by kylewm** [comment]
:+1: That's the answer I wanted!


On Tue, Jan 12, 2016, at 10:26 AM, Ben Werdmuller wrote:
> @kylewm[1] Sorry for late reply - I think we should just update the
> plugins. I see you've sent some pull requests, which I really
> appreciate!


> — Reply to this email directly or view it on GitHub[2].


>



Links:

  1. https://github.com/kylewm
  2. https://github.com/idno/Known/issues/1132#issuecomment-171002695
