### ISSUE TITLE
A place to put utility functions?

### ISSUE THREAD

**Issue by benwerd** [idno/Known#1192]
Should Known have a place to put general-purpose utility functions? Right now there's no way for plugins to do this, and core kind of fudges the issue by sticking them in the Idno class.

cc @kylewm, who brought it up in a PR.

**Comment by kylewm** [comment]
It's definitely a tradeoff. Util can be a magnet for random crap that would probably be a better fit somewhere else, and that's why I'm kind of impressed you don't have something like that.

But it would be nice to have a place to put functions and classes that basically augment the stdlib. (in my case, I would have liked to add `iterator_map` to complement `array_map`)

**Comment by mapkyca** [comment]
Shouldn't plugins just put stuff in their own namespaces...?

**Comment by benwerd** [comment]
Closing this out. Let's leave stuff in its own namespaces - and create a new namespace if necessary.

**Comment by kylewm** [comment]
:+1:
