### ISSUE TITLE
Micropub : list of connected applications

### ISSUE THREAD

**Issue by danito** [idno/Known#1225]
I tested some tools from p3k.io like quill. Now I would like to revoke some of those applications, but can't find a way how. Isn't there a way to see what application of what rights?

**Comment by kylewm** [comment]
Not yet but that's a great idea.


On Sun, Feb 14, 2016, at 12:07 PM, Daniel nix wrote:
> I tested some tools from p3k.io like quill. Now I would like to revoke
> some of those applications, but can't find a way how. Isn't there a
> way to see what application of what rights?


> — Reply to this email directly or view it on GitHub[1].


>


Links:

  1. https://github.com/idno/Known/issues/1225

**Comment by danito** [comment]
... and be able to revoke their token.

**Comment by kylewm** [comment]
This surfaces an interesting issue, that we create multiple (sometimes many) keys for a given client id. Couple possibilities:

* don't generate a new key for an existing client_id/scope combination. instead give out an existing key (whether this is a good thing is a security question that I don't know the answer to)
* on the config screen, group by client id, so that we just show one "woodwind.xyz" application even if it has issued several keys. revoking access would revoke all of those keys
