### ISSUE TITLE
Run db->optimize() manually

### ISSUE THREAD

**Issue by kylewm** [idno/Known#1247]
The call to `\Idno\Core\Idno::site()->db()->optimize();` when you first open the site configuration page takes a non-trivial amount of time to run (~15 seconds). Even after throttling it to once a day, it still irritates me, and if I didn't know why it was taking so long, I would be even more impatient.

I think I'd like to add a button to invoke it manually (also via the console script, so you could run it in a cron job) and stop doing it on page load. I could make this a configuration option if it's still advantageous to run it automatically for most sites.

**Comment by benwerd** [comment]
Yeah. I think you're right - anything that lags page load should probably
be wiped.

I'm wondering if having a cron job hook wouldn't be a bad call (perhaps
with a token in the URL to prevent external attacks). You could then
automatically trigger some back-end tasks, like this, to run regularly. For
shared hosts that can't easily run cron jobs we could trigger via Convoy.

On Tue, Feb 16, 2016 at 11:26 AM, Kyle Mahan <notifications@github.com>
wrote:

> The call to \Idno\Core\Idno::site()->db()->optimize(); when you first
> open the site configuration page takes a non-trivial amount of time to run
> (~15 seconds). Even after throttling it to once a day, it still irritates
> me, and if I didn't know why it was taking so long, I would be even more
> impatient.
>
> I think I'd like to add a button to invoke it manually (also via the
> console script, so you could run it in a cron job) and stop doing it on
> page load. I could make this a configuration option if it's still
> advantageous to run it automatically for most sites.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/1247>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by mapkyca** [comment]
+1 for the cron hook

**Comment by mapkyca** [comment]
Another thing to consider, assuming the db is still available at that point (it should be), is to run the command on a shutdown hook. That way it'll run after the page has rendered.

**Comment by kylewm** [comment]
Works for me!

**Comment by mapkyca** [comment]
Another thing, the vendor service ping is also done on this thread, which can take a little time (and times out behind a firewall).

I wonder if we should do this a little smarter as well..

**Comment by kylewm** [comment]
I'm still getting a long delay loading the /admin page the first time (tested w/ both nginx and apache). It looks like at some point, php's behavior changed to process shutdown functions before closing the connection to the user:

> In PHP 4.0.6 and earlier under Apache, the registered shutdown functions are called after the request has been completed. Since PHP 4.1, the shutdown functions are called as the part of the request so that it's possible to send the output from them. There is currently no way to process the data after the request has been completed.

https://bugs.php.net/bug.php?id=20447

We may need to use the `header("Connection: close")` trick employed elsewhere (http://php.net/manual/en/function.register-shutdown-function.php#40815)

**Comment by benwerd** [comment]
I think I need a tag for "is it too late to rewrite this in Go?"

I'd like to explore having an asynchronous code function in general - not just for this, but for a bunch of functionality across the board. I don't know how possible it'd be, but it would be nice to have bits of garbage collection, and other things, handled in an unobtrusive way for the user. Making webmention processing asynchronous would also be wise, of course.

Now, does this block use the connection close trick? Maybe. That might be the best we can do. But I'd love to hear other ideas.

**Comment by mapkyca** [comment]
Gosh. Every day is a school day. Wasn't aware of the change in behaviour - looks like there was also a change between 5.1 and 5.2.

Hmm... @benwerd We could use process control or fork, however those functions are often blocked for security reasons, so is not something you can rely on.

There are two options I can see: 1) we have a cron script, which might be the easiest thing to do for this sort of thing, but is *another* install step and many folk don't have access to their crontab. 2) we have a background process queue program that we can farm this sort of thing off to, but given that we're writing a web app not an operating system, this might be overkill, and introduces issues of its own.

Regarding the specifics of optimise... I've always thought this was a bit of a fudge, and the kind of thing the DBMS really *should* be handling itself, along with synchronisation and table repair. My feeling on this specific issue is that we shouldn't try and do it (especially since running the query causes more noticeable problems for folk than a slightly un-optimised db table), and we leave this kind of thing for the DBMS / OS install to do, which is really where the work should be.

**Comment by tinokremer** [comment]
In addition to what @mapkyca wrote:- Many shared webhosts already do maintenance on their seperate database server where things are optimized, indexes are updated, consistency checks are done.

That excludes any Known specific things obviously.

**Comment by mapkyca** [comment]
Another thought; we could have this sort of thing - optimise, vendor message fetch, on their own endpoints and call them via javascript. 

I might build this out, but I strongly suggest we merge #1149 first.
