### ISSUE TITLE
Allows upload/playback of video on Android, fails to playback on other platforms

### ISSUE THREAD

**Issue by neilr8133** [idno/Known#1373]
## While trying to do this:

I tried to post a video from my Android/Firefox browser by clicking on the microphone icon (`/media`) and it worked!
## I encountered this error:

...but people on iOS can't see it.
## Some other notes:

Research suggests that the iOS browser won't play it back because the MIME type (audio, not video) is not correct, however I have not dug into this extensively.

**Comment by neilr8133** [comment]
Addendum: The posting and playback of the video worked great in Firefox on Android, and Windows-based Firefox was also able to play it back.

**Comment by kylewm** [comment]
I think the right thing to do here is probably to restrict uploads to only audio files. This plugin is definitely not set up to handle arbitrary media files, as you discovered :P

**Comment by tinokremer** [comment]
Video is a whole different ballgame as you actually need to transcode in order to service all kinds of devices. I currently use YouTube instead. I upload it there, set the privacy to "unlisted", get the snippit html code and post that in a normal "post". For a number of users that would be the best way anyway as video files are potentially quite big. On YouTube you can post them for 'free' while most hosting accounts are capped at a few Gigabytes at most.

**Comment by mapkyca** [comment]
Closing, this is out of scope of the plugin. 

While video upload is "supported" kindof by the original media plugin, it's a whole can of worms to get working right, so really this isn't a supported feature right now.
