### ISSUE TITLE
A reply to a post that is not POSSEd to twitter should include the replied-to post's URL when POSSEd to twitter

### ISSUE THREAD

**Issue by kevinmarks** [idno/Known#1396]
## While trying to do this:

When I use Known to reply to a post in Woodwind or using the Known bookmarklet, I don't know if the linked-to post will be sent to twitter.
## I encountered this error:

If the post I'm replying to was POSSEd to twitter, then Known sets the in-reply-to correctly on the POSSEd copy. If it wasn't, then there is no cue that ti was a reply to anything.
## Some other notes:

This post was not POSSEd to twitter:
http://known.kevinmarks.com/2016/time-is-hard---this-post-was-from-the-future
This reply to it was:
http://known.kevinmarks.com/2016/kylewmhan-if-i-reply-to-this-on-known-and-posse
https://twitter.com/kevinmarks/status/718181774816219136

Note that the twitter version has no indication it was a reply to anything

This post, replying to the 2nd one (which was POSSEd to twitter):
http://known.kevinmarks.com/2016/kylewmahan-replying-to-a-possed-post-does-set-the-in-reply-to

does set the in-reply-to on twitter, showing the thread:
https://twitter.com/kevinmarks/status/718182609000341505

So, when there is a POSSE to twitter of an in-reply-to post, and the post being replied to does not have a twitter POSSE copy, Known should put the URL of the post being replied to in the twitter POSSE copy.

**Comment by kylewm** [comment]
fwiw, we handled this in Red Wind and Bridgy but simply *not letting* you POSSE a reply to Twitter if we can't find the ID of the tweet being replied to.

in silo.pub, I do something more like your suggestion -- construct a tweet of the form:

```
"Re: https://url-being-reply-to, I disagree with you!"
```

Although tbh, I never want to tweet something that looks like that :P

**Comment by kevinmarks** [comment]
Right, but when I'm reading an indie post in woodwind, I don't know if it
has a POSSE copy, so I am not sure what will happen when I reply there; the
'reply without context' is odd as well.

**Comment by snarfed** [comment]
lots more discussion on the use case and tradeoffs in snarfed/bridgy#362 (and another request in snarfed/bridgy#622).

**Comment by benwerd** [comment]
I'm not in favor of invisibly syndicating text to Twitter that you didn't explicitly write.

Reading between the lines, one obvious thing to do is to make syndicated copies clearly encoded in the feed (albeit not necessarily visibly - that's publisher's choice), so that readers like Woodwind know what to do with them. While syndicated copies themselves aren't guaranteed to have a link back (as most of Known's on Twitter don't, for space reasons), I think it's fair to dictate that the canonical versions should link out to their copies.

**Comment by kylewm** [comment]
> I think it's fair to dictate that the canonical versions should link out to their copies.

I pretty much agree with that -- the experience of replying from Woodwind in general has gotten better since Known started including u-syndication (invisibly) in the h-feed

On the flip side, the /share page (reply bookmarklet) has some logic that pre-selects syndicate-to-Twitter when replying to a twitter.com URL. We should enhance that so it does the same thing when replying to a post that is syndicated to Twitter (the Share handler already fetches the page, so it shouldn't add any HTTP overhead)

**Comment by kylewm** [comment]
Also if @kevinmarks or anyone has examples of POSSEing a reply to Twitter when the original is not POSSEd, I would like to see it -- I was looking for real world examples to drive the Salmentions discussion yesterday and couldn't find any

**Comment by benwerd** [comment]
Agree re: finding syndicated versions. Reply threading (theoretically) works through syndicated URLs, and this really should too. I guess it should probably add the @-reply prefix, too, although maybe it's okay to invisibly prepend that in this case. But then you have the character limit issue, so perhaps the counter should decrement accordingly. But then again, that's weird if you don't know what's going on and why.

**Comment by kevinmarks** [comment]
Kyle POSSE of a reply when the original wasn't is in my bug report - that's
the sue case. The character limit issue is tricker when it's woodwind's
editor though.

**Comment by kylewm** [comment]
Heh, sure but that was a test to see what would happen. I was looking for people who routinely intentionally post replies to Twitter, to help inform the discussion on https://github.com/snarfed/bridgy/issues/458

(If no one does it in practice, then we don't need to think too hard about how Bridgy works with salmentions)

**Comment by kevinmarks** [comment]
Well, that was a demonstration of the issue. My original motivation was using micropub in woodwind to respond to things via known and not knowing what the twitter version would look like if I checked the syndication chiclet.

**Comment by kylewm** [comment]
Not sure why we're arguing, I understand the issue. My question about real world examples was only tangentially related.
