### ISSUE TITLE
Cannot disable "default" plugins

### ISSUE THREAD

**Issue by pstadt** [idno/Known#1427]
With release 0.9.2 I tried to disable the plugin "Public Comments" aka "Comments".
The Admin GUI always reported "The plugin was uninstalled." but every time it was marked "enabled" again in the list (and the plugin was active).

For a test I removed in Idno/Core/Config.php from config -> plugins Comments and Media.
Now I was able to disable those two plugins via Admin GUI and they were no longer active.
I cannot disable all other listed "default plugins", so it looks like this list of initial? default plugins is merged in at a time into the list of active plugins.

**Comment by rikmendes** [comment]
There is a simple switch to turn plug-ins completely off on the config.ini
at the root of your known installation.

I'm outdoor right now can't check it up but it's on the documentation.

**Comment by pstadt** [comment]
No, I don't want to disable all plugins. I only want to disable specific plugins, but I cannot disable those plugins which are listed in Idno/Core/Config.php as default. They are automatically reenabled all the time.

**Comment by kylewm** [comment]
@pstadt I think this is a bug, but you can work around it with the config setting Rick was alluding to. You'd want to set:

```
antiplugins[] = 'Comments'
```

in config.ini

**Comment by kylewm** [comment]
This change seems to be the culprit: https://github.com/idno/Known/commit/3db80d2bf432eb11c9a163b01391e2eacc920cd5 specifically the change from `array_merge` to `array_replace_recursive`.

If I have a list of default plugins:

```
array(
 [0] => "Status",
 [1] => "Text",
 [2] => "Comments",
 [3] => "Twitter",
)
```

and try to "replace" that with the saved set of plugins from the DB (where Comments has been disabled -- notice that index 2 is missing):

```
array(
 [0] => "Status",
 [1] => "Text",
 [3] => "Twitter",
)
```

then I get the original array again, with Comments restored.

**Comment by rikmendes** [comment]
You dont need to disable all plugins. that's the point of config.ini : to disable or enable specific items without having to mess in the code.

**Comment by pstadt** [comment]
@rikmendes I don't want to mess with the code. See it as a kind of debugging support to understand the problem.

**Comment by cannod** [comment]
Have just installed a fresh install of 0.9.2 and can confirm that I also see this bug. Disabling a Plugin from Plugins page does not work as @pstadt described.

**Comment by matunixe** [comment]
Same here.

**Comment by kreativmind** [comment]
Just delete the folder of the plugin you don't want to use from your idno/plugins folder and all is well. It will go away from the site and your homepage too will reflect that as well. For example, delete the media plugin folder and you will see that audio is no longer in the enable/disable plug-ins list and also, the homepage will not show the icon to create a new audio post anymore.

**Comment by benwerd** [comment]
This will be fixed in the next release.

**Comment by mapkyca** [comment]
Is this still an issue on the current version in git?

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1427" class="u-in-reply-to"></a>I've been looking into this a little bit as part of addressing some other issues and I think we have a conceptual conflict going on somewhere... basically we're setting a "initial_plugins" default, which is merged with the database loaded version and replaces any missing values (since it's not possible to tombstone or anything).

Interestingly, if there is a host specific config.ini present the ini loaded version of "initial_plugins" is unset, which explains why we're seeing this on hosted and some self hosted services, but I'm not seeing it on my own site (which uses host specific configs).

I think the least worst option would be to unset the ini loaded version of "initial_plugins" if a database defined version is present. This will allow plugins to be toggled and a site created with an initial list of activated plugins... however it will prevent us from using initial_plugins to activate new plugins on old sites by modifying the config file.

Given that initial_plugins is unset before loading host specific ini files, I'm guessing this was the intent...
