### ISSUE TITLE
do not modify the uploadpath with domain name

### ISSUE THREAD

**Issue by jangalinski** [idno/Known#1439]
## While trying to do this:

setting the uploadpath to a fixed path

## I encountered this error:

the path is extened via domain name

## Some other notes:

I do  not want the domain name to be part of the upload data, as I use local *.dev domains to set this up and then push it to the server.

**Comment by physcocode** [comment]
+1

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1439" class="u-in-reply-to"></a>Namespacing is needed for multitennant sites, there might be a case for an override in config.

**Comment by mapkyca** [comment]
Going to close this since it's rather old, and I don't think myself or any other community developer has the bandwidth to do it.

However, I'm sure pull requests will be gratefully received and reviewed. A suggestion for how it might be implemented: 

* domain paths are only really needed for multitennant, so perhaps only activate for those installs
* We don't want to do this for existing installs, since existing data is already loaded to $upload_path/$DOMAIN
