### ISSUE TITLE
Cannot get static pages to work while upgrading to latest version

### ISSUE THREAD

**Issue by binitprads** [idno/Known#1440]
## While trying to do this: 

upgrade to the latest version of Known (0.9.2)

## I encountered this error:

The whole site doesn't work and error is

PHP Fatal error:  Can't use function return value in write context in /public_html/known/IdnoPlugins/StaticPages/Main.php on line 51

## Some other notes:

If i a remove the above folder (i.e. StaticPages) then the site works, but of course without static pages functionality.

would you know how to resolve this?

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1440" class="u-in-reply-to"></a>What's your PHP version?

**Comment by binitprads** [comment]
It was 5.4. I changed to 5.6 and everything is working great now. Thank you!

**Comment by kylewm** [comment]
Upgrading PHP is the best solution, but we should still fix this backcompat issue (especially since it's an easy fix)

Thanks for reporting @binitprads!

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1440#event-665253846" class="u-in-reply-to"></a>Yep, moving to 5.6 is the recommended solution to this sort of thing (although this specific issue should be fixed in git now).

For the benefit of the tape, PHP 5.4 is EOL, so increasingly supporting in will become less and less practical.
