### ISSUE TITLE
Menu class="active" missing on subdirectory menus

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#1463]
## While trying to do this:

Using menus
## I encountered this error:

active class doesn't get applied
## Some other notes:

This is because REQUEST_URI doesn't match when Known is installed on a subdirectory.

**Comment by rikmendes** [comment]
not directly related to this fix but I noticed the "notifications" menu is gone from the main menu since last 2 weeks on the github code. got this on my instance after last week git pull. 
![screenshot_206](https://cloud.githubusercontent.com/assets/12155003/15626829/c15abf52-24cf-11e6-800d-2ecb933fac72.png)

**Comment by kylewm** [comment]
@rikmendes see https://github.com/idno/Known/commit/a3ad6f9003da66645dad116b86653f3ce38e00f8

> Commenting out notifications for now
> They need a little more TLC before they hit primetime

**Comment by physcocode** [comment]
isn't this fixed ?
