### ISSUE TITLE
Migration to known....

### ISSUE THREAD

**Issue by TheOtterslider** [idno/Known#1464]
I'm trying to migrate my current Joomla site -- I say site, but think blog -- to known.  I couldn't find any tools to do it (and I couldn't make my joomla site export xml that known liked) so I thought I'd write my own.  I looked at the database and it didn't look too hard.  

I import the articles into entities then I import stuff (individual rows with access, owner, body, inreplyto, tags, slug, created, updated, _id, uuid, and entitiy_subtype) into metadata too.  But the things don't show up.

Can someone point me in the direction and let me know what I may have missed?

**Comment by TheOtterslider** [comment]
Wait...I just found this:  https://github.com/idno/Known/issues/734  Looks like I need to sort out the post activity

**Comment by kylewm** [comment]
@TheOtterslider we actually removed `ActivityStreamsPost` a little while back, so that should not be an issue anymore.

Does it make sense how the `metadata` table works? It basically acts as an index for the big JSON blob in the `entities` table ... so you can look up entities by their attributes. Populating it is tricky to get right by hand.

When I did a custom migration to Known, I found the easiest thing to be writing a little php that created the Known entities and saved them directly -- rather than attempting to do it with SQL. This is very specific to my particular site/data, but in case it gives you some ideas, here's the script I used: https://gist.github.com/kylewm/7b1a757e605d2323be8b116ab209f879

**Comment by TheOtterslider** [comment]
@kylewm -- yeah...After I went and looked, I couldn't find anything related to that.

>Does it make sense how the metadata table works?
Well, I thought so until it didn't work  ;)

Thanks for the pointer to the script.  I'll take a look at it.  I'll probably end up just doing something similar.

**Comment by kylewm** [comment]
Let's take this conversation over to the mailing list, so others can benefit from anything we figure out :) https://groups.google.com/forum/#!forum/known-dev
