### ISSUE TITLE
Duplicate posts and memory exhausted while trying to remove them

### ISSUE THREAD

**Issue by Phyks** [idno/Known#1469]
Hi,

I am using an up to date version of Known (v0.9.2) and am encountering some issues with duplicate articles.

See [this search on my blog](https://known.phyks.me/content/all/?q=velib):
- Except from the first item on this page, all the results are duplicated articles. I am not sure how it actually happened.
- When I try to delete it, I get

```
Fatal Error: PATH_TO_KNOWN/Idno/Core/Webservice.php:270 - "Allowed memory size of 134217728 bytes exhausted (tried to allocate 129765377 bytes)", on page known.phyks.me/status/delete/0646020354b168aefde0d21ed82d7201
```

(note also the full path exposure here, although it should be behind an authentification so may be mostly ok)
- Finally, there is an "Older" link at the bottom of the page which sends to [this](https://known.phyks.me/content/all/?q=velib&offset=10):

> We couldn't find anything that matches your search.

Thanks!

**Comment by mapkyca** [comment]
I'm guessing it's trying to send a webmention delete to something.

Question for the floor... is there any reason why *outgoing* webmention pings don't just HEAD rather than GET?

**Comment by mapkyca** [comment]
Ahh... answered my own question, still I can't help feeling that the ping could be done more efficiently...

**Comment by kylewm** [comment]
for clarity, outgoing pings should be POST

**Comment by mapkyca** [comment]
Yeah, I was getting mixed up with the endpoint extraction, which was get. For me it'd make sense to include the endpoint link in the headers so you don't have to fetch the entire page (in rare instances huge and causing problems especially when chucked into the MF2 parser), but that would eliminate static pages.

Perhaps modifying the read functions to use a file descriptor rather than just fetch the entire url...
