### ISSUE TITLE
Timezone offsets are not handled properly (eg in events)

### ISSUE THREAD

**Issue by benwerd** [idno/Known#15]
##

**Comment by mapkyca** [comment]
Any more details on symtoms here... seems to work ok for me...

**Comment by benwerd** [comment]
Timezone offsets aren't great if your server time and your local time as a user are different. Parsing / display is inconsistent.

Better would be to actually ask the user for their timezone and display accordingly - or, even better, work out which timezone is local based on the location in the case of events ... ;)

**Comment by mapkyca** [comment]
Servertime/localtime differential if someone has done something dumb such as set the system clock to anything other than GMT... which shouldn't happen but does on some poorly configured virtual hosts, or windows machines.

**Comment by benwerd** [comment]
Display / detection still doesn't work well if the user's local time is different. It'll display times in UTC, which obviously sucks if you live anywhere else.

**Comment by mapkyca** [comment]
Hmm... 

That is possibly a bug / setting in the JS library then. Basically all times *should* be in GMT, because that's what time it actually is. Agreeing that makes it possible to locally convert to any timezone offset you wish. It's a mistake to only store wallclock time...

I wonder if timeago has a localise setting, taking a GMT time and converting it via localised setting in the browser? Sounds like something it *should* do...

**Comment by benwerd** [comment]
All times should be UTC internally, yep.

Timeago isn't run on the event fields. This ticket predates use of timeago on post endings - but here it's still valid for event starting and ending times.

**Comment by mapkyca** [comment]
Ahh... gotcha....

Perhaps we should write a bit of JS to do the conversion... seems to make sense for the server output the start and end as UTC, but for the browser to quietly rewrite them.

The local browser has a better idea of where it is than the server, plus generating a custom view of an even for each person/location causes merry hell with caching...

**Comment by mapkyca** [comment]
Could probably do something with moment.js...

**Comment by kylewm** [comment]
I think I'd prefer to have publish dates displayed in the author's timezone, rather than the reader's. Having an admin setting about what your local timezone is solves the 90% case here (for people who don't change timezones frequently ... and the last 10% would require aaronpk-like location tracking). I think that argues for rendering the date with author's timezone on the server side.

Events should probably have an explicit timezone associated with them (e.g. even though my site is in Pacific time, I might post an IWC event in NYC or Boston)

**Comment by mapkyca** [comment]
Yeah, good points all... agree.
