### ISSUE TITLE
Alt attribute for Image Posts (accessibility)

### ISSUE THREAD

**Issue by wobintosh2** [idno/Known#1548]
It would be good to have a possibility to add an alt Attribute for image posts (better accessibility for people with screenreader)

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1548" class="u-in-reply-to"></a>Any particular why we can't just use the photo title for this and add it automatically? Presumably the two will be related...?

Not too keen to add another for field if it can be avoided, since most folk neither know or care about what an alt tag is...
