### ISSUE TITLE
Known doesn't pass Webmention Rocks test 1

### ISSUE THREAD

**Issue by benwerd** [idno/Known#1589]
## While trying to do this:

Webmention this URL: https://webmention.rocks/test/1

## I encountered this error:

Alas, we seem to be stuck on relative webmention URLs.

## Some other notes:

This appears to be the only blocker to passing the Webmention Rocks suite.

**Comment by mapkyca** [comment]
Looks like a bug in the upstream mention client.

The regex in _findWebmentionEndpointInxxxxxx() needs some tweaking. They're protected, so we could potentially override this in our webmention wrapper.

**Comment by kylewm** [comment]
huh, it certainly used to. just verified with my old installation: https://webmention.rocks/test/1

**Comment by aaronpk** [comment]
If I remember correctly, Known uses a forked version of https://github.com/indieweb/mention-client-php that I wrote ages ago. I have since updated it to pass all the webmention.rocks tests since that's what my webmention sending client uses now. You could update the library in Known from the latest mention-client-php to fix this.

**Comment by mapkyca** [comment]
Just tried, seems to have been fixed at some point...
