### ISSUE TITLE
Warning: Cannot modify header information

### ISSUE THREAD

**Issue by jeremycherfas** [idno/Known#1633]
## While trying to do this:

Create a post from micropublish.net to known at vaviblog.com

## I encountered this error:

> There was an error making a request to your Micropub endpoint. The error received was: Couldn't create note
> Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php:213) in /var/www/html/Idno/Core/Session.php on line 339

## Some other notes:

This is surely related to [issue 1596](https://github.com/idno/Known/issues/1596) although the specific error does not occur in the errors listed in that issue.

The error occurs no matter what kind of post I try to create with micropublish.net

**Comment by mapkyca** [comment]
Notice errors should be removed, but unless you're running Known with warnings as errors (pedantic_mode = true in config.ini) you should be able to suppress them in your PHP ini, so that they don't become visible (and prevent headers being sent), which is a fairly common production configuration.

This isn't related to #1596 - the triggering error is something in the micropub endpoint, although I can't see anything obviously wrong, so might have been fixed in a later release.

**Comment by mapkyca** [comment]
Could you provide some more detail on how to replicate the micropub endpoint error?

**Comment by jeremycherfas** [comment]
1. Go to micropublish.net where I am signed in as `https://vaviblog.com/profile/jeremy`  
2. Create any type of post; I just tried with a repost; i have tried the others too.  
3. Fill fields. I leave Category, Syndicate to and Slug blank  
4. Click on Create  
5. Get error

**Comment by mapkyca** [comment]
Thinking this should have been fixed, either way my code doesn't track since line numbers have changed in master and I don't know what build this is on. 

Might be worth reconfirming against master.

Additionally, notice errors probably shouldn't be being echoed on production, so looks like there are some server side config issues that might be worth addressing in the mean time...
