### ISSUE TITLE
Feature Request: Make it easier to add audio to body of post.

### ISSUE THREAD

**Issue by tjspann** [idno/Known#1663]
## While trying to do this:
I'm using Known to power the news feed for my company's website. It seems even though Known includes the audio file in the RSS feed, most websites do not pull that info, thus not displaying the audio.

Would it be possible to add some code so that when editing an already published audio post, the page displays the link to the audio file, as well as giving the option to change or remove it?

**Comment by mapkyca** [comment]
These seem to be two separate things: 

1) Audio not being picked up by RSS reader (possible bug, although if the reader doesn't understand the podcast extensions there's not much we can do)

2) Be able to edit audio on an existing post (feature, and yes I agree that would be useful).

Or did I misunderstand? :)

**Comment by mapkyca** [comment]
Also, might want to try latest master, since I just pushed a few itunes related bits

**Comment by tjmidnight** [comment]
Yes, that is it exactly. Due to some or even most RSS readers not being up to date on feature-set, the main audio file does not show up. The feature I'm requesting would be number two to help to get around that. I work for a broadcast station which would often make posts with multiple audio files if allowed. 

FULL DISCLOSURE: I've been slammed at work and am just now getting to this. If this has already been addressed or the latest master helps out with this I will certainly give it a shot tomorrow when I'm back at work. In which case feel free to ignore this comment entirely. :)
