### ISSUE TITLE
Image quality greatly reduced when uploading photos

### ISSUE THREAD

**Issue by cleverdevil** [idno/Known#1924]
## While trying to do this:

Publish a photo via the web interface or via Micropub media endpoint.

## I encountered this error:

The uploaded image gets thumbnailed down to a very low quality, and the original image seems to be discarded.

* Here is an image that was uploaded via the Micro.blog macOS app, using the Micropub media endpoint: https://cleverdevil.io/2017/microblog-is-now-my-primary-social-media-timeline
* Here is the original image that I uploaded: http://share.cleverdevil.io/87uG6DtOwe.png
* Here is another example from an image I uploaded from my iPhone, running iOS 11, in Safari through the web interface: https://cleverdevil.io/2017/that-was-a-fun-test-drive
* Here is the original photo: http://share.cleverdevil.io/LtXCLf83Lt.jpg

## Some other notes:

I am running the latest from Git master:

```
🕷  cat version.known
version = "0.9.9"
build = 2017101301
```

The server is an Ubuntu 16.04.03 VM running Apache:

```
🕷  apache2 -v
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2017-09-18T15:09:02
```

My current PHP version:

```
🕷  php -v
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
```

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known/issues/1924" class="u-in-reply-to"></a>Ahh, no... that was a deliberate change that was made some time back. 

I think this was done because having title link to the permalink, and the image to a different place, was confusing. 

The original is still there, and is even exposed through the data-original-image attribute.

I could see an argument for linking to the original image if the photo is displayed in a permalink rather than a stream though...

**Comment by cleverdevil** [comment]
Cool, yeah, I think that'll help significantly, making it much more obvious how to get to the original image. I'll test it out once it lands in master here.

I still think that the code that generates the thumbnail is overly aggressive on how far down it scales the quality. Would you be open to making that a configurable thing somewhere? I'd prefer to ramp up the quality (and file size) at the expense of page load time.
