### ISSUE TITLE
Retroactive posse

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#206]
Be able to posse already posted items in edit

**Comment by benwerd** [comment]
Bumping. Retroactive POSSE and de-POSSE both.

**Comment by mapkyca** [comment]
Bumping again, since it's been brought up in discussion more than once recently...

**Comment by benwerd** [comment]
Yeah. Would be super-cool. Haven't had time, and the UX is important, but it's massively necessary.

**Comment by mapkyca** [comment]
Bumping this again. Might try and implement it shortly...

**Comment by benwerd** [comment]
Nice. I definitely have some thoughts on this. We do have some of the components to make this work.

**Comment by kylewm** [comment]
I'm thinking through the UX a little, and it's definitely tricky. In Red Wind, it's always worked like: you edit a post, toggle the targets you want to syndicate to, and click save to POSSE to them. Clicking "Edit" in order to syndicate has always felt a little off to me; like clicking "Start" to shutdown the system.

I played around a little with an alternative; a screen specifically for syndicating. You click the "Syndicate" link

![syndicate-link](https://cloud.githubusercontent.com/assets/950127/12282761/83ade84a-b955-11e5-8515-6d8210191069.png)

to bring up the syndication page which just has the item rendered and the syndication toggles at the bottom

![syndicate-form](https://cloud.githubusercontent.com/assets/950127/12282762/85be9260-b955-11e5-896d-e684eeb59bac.png)

I dunno, it's functional but definitely feels janky in its own way.

And oh man de-POSSEing would be amazing (I see you feature creeping!), and definitely complicates things. Accidentally deleting a POSSE copy could be a disaster (I'm imagining like deleting a Medium post and losing a permalink that's been shared around). That *doesn't* really feel like something you should be able to do from the edit screen (?)

**Comment by benwerd** [comment]
I'd say if you can remove the POSSE from the edit screen, it hits you with a bunch of confirmation errors. Not something you can accidentally click. Having the mechanism to remove POSSE also allows you to do things like effective snapchat: post a status update on Twitter for 30 seconds and then pull it, automatically. Suddenly content only needs to show up on a social network for as long as you want it to.

**Comment by kylewm** [comment]
> 2) if ->posse contains $service we set disabled

There's a bit of an impedence mismatch now that each service has account as part of its identifier too

The syndication target is `twitter::kylewm2` and the  posse field looks like `["twitter" => [ "identifier" => "@kylewm2"]]`. There's not a general way to convert from one to the other yet.

**Comment by matzoman** [comment]
I'm working on this issue. 
Right now I'm not sure how I can disable a button in edit mode when the entry is already POSSE'd to the service.

getPosseLinks() and getServiceAccounts($service) do not match, right?

**Comment by kylewm** [comment]
@matzoman yes, that's exactly where I got stuck too. I think what I'd do is add a field to PosseLinks called "account" or "serviceaccount" so you'd have like

```json
{
    "twitter": { 
        "url": "https://twitter.com/someuser/1234", 
        "identifier": "@someuser",
        "serviceaccount": "twitter::someuser",
    }
}
```

It would only work for POSSEd posts going forward but I think that's the best we can do.

**Comment by benwerd** [comment]
Seconded ;)

**Comment by benwerd** [comment]
I've updated the Twitter plugin but will need to update Facebook etc later.

**Comment by matzoman** [comment]
S.th. Else i noticed: the save function is calling the syndicate function, better seperate because the syndicate trigger event of the Twitter plugin for example are calling save again. --> possible endless loop 

(I hope this makes sense)

**Comment by matzoman** [comment]
moving 'syndicate' outside of 'save' means changing every plugin --> not the best solution, but more clean code?

**Comment by kylewm** [comment]
> syndicate trigger event of the Twitter plugin for example are calling save again. --> possible endless loop 

I absolutely agree, and I'm pretty sure I heard Ben mention this too. Too many events are triggered by simply saving an Entity (which happens all the time, e.g. whenever someone comments).

I think we should add a function `Entity::publish` that would only be called when the user actually clicks "Publish". `publish` would call `Entity::save` and then:

1. (Optionally) Add it to the feed
2. Call syndicate

This would be useful for saving Drafts in the future too; i.e. we could save without publishing them.

**Comment by kylewm** [comment]
> moving 'syndicate' outside of 'save' means changing every plugin --> not the best solution, but more clean code?

I vote yes, especially if you can do it in a way that outdated plugins degrade gracefully.

**Comment by benwerd** [comment]
I strongly agree with adding `Entity::publish` and modifying every plugin.

**Comment by matzoman** [comment]
Today I worked on adding `Entity::publish` and modifying the plugins. ("photo" worked: yay!)
The next step would be to disable the buttons when the entry was already POSSE'd. maybe tomorrow.
([my branch: Retroactive-posse](https://github.com/matzoman/Known/tree/Retroactive-posse))

**Comment by benwerd** [comment]
@matzoman this sounds completely awesome!

**Comment by matzoman** [comment]
@benwerd just a heads up: [Twitter Pull Request](https://github.com/idno/Twitter/pull/37) small fix for your changes in the twitter plugin.

about this issue: I made progress, pull request follows maybe on monday.

**Comment by kylewm** [comment]
Thanks again @matzoman!

**Comment by benwerd** [comment]
Incredibly cool!
