### ISSUE TITLE
Reauthorizing tokens for POSSE channels

### ISSUE THREAD

**Issue by erinjo** [idno/Known#216]
My Facebook token expired.  We need an easy way to handle this with customers if FB deauthorizes all apps after a certain period of time.  I'm attaching the email I got from ThinkUp that (I think) deals with the same problem.

To be honest, I can't figure out how to fix this, either from within my Idno or from within my Idno dev account on FB. 
![screen shot 2014-03-31 at 12 42 30 pm](https://cloud.githubusercontent.com/assets/1192220/2597391/95fbf8b8-bab3-11e3-945c-708bd0a1f202.png)
![screen shot 2014-04-02 at 3 06 11 pm](https://cloud.githubusercontent.com/assets/1192220/2597392/99909cea-bab3-11e3-8f76-162b85251f51.png)
##

**Comment by mapkyca** [comment]
Related #718

**Comment by kylewm** [comment]
FWIW, Bridgy [sends a push notification via Facebook](https://github.com/snarfed/bridgy/blob/5826ade115a5ce8a5765dbe7392ffc1a72e1fa9e/facebook.py#L144) when your token expires. 

Unfortunately, for some reason this requires the app to have the `canvas` permission, which is a royal PITA to get. I think Bridgy only has it because it was grandfathered

**Comment by mapkyca** [comment]
Going to close this because it's a per plugin issue, but the "correct" way of this should be to store the renewal token and expiry as well as the auth token, then when time()> expiry use the renewal token to reauth.
