### ISSUE TITLE
Deleting some spam comments fails. 

### ISSUE THREAD

**Issue by sikkdays** [idno/known#2243]
Similar to this closed issue #1403 when I try to delete some comments, my known blog jumps to a login page, even though I'm logged in and using HTTPS. It is leaping to an HTTP login. 

Using the suggestions in #1403 I do notice that the delete link is an http link. Why? Is it the difference of people using HTTP to reach my site and HTTPS? 

Diagnostics on the admin page show no issues. Using version 0.9.9 on MsSQL.

**Comment by danito** [comment]
Hi,
yes, when one opens your site with http and comments there, the delete link will be with http://, but as you're logged in with https the link is not working for you.
So you need to login into the http site to be able to delete the comment.
That's why I forward all http requests to https (.htaccess) so that I force visitors to use the https version.

**Comment by sikkdays** [comment]
Logging in during an http session still did not allow me to delete. 
After posting this comment, I did change .htaccess to force https because I'm getting hit with a ton of spam. 
So I suppose this issue can be closed, but I am curious how to remove those comments? Will I have to learn SQL, so I can dig into it?
