### ISSUE TITLE
Remove Bootstrap

### ISSUE THREAD

**Issue by benwerd** [idno/known#2325]
There's no need to have Bootstrap loaded in 2019. Known can use CSS grids and have a significantly lighter weight interface.

This probably means having a Bootstrap shim for people who want to use older templates.

**Comment by physcocode** [comment]
wow , what about other elements like cards, button etc ?

**Comment by cleverdevil** [comment]
I'm good with this, but as a plugin developer, I'll likely want to have plenty of time to test before upgrading 😀 Oh, and documentation on how to make the transition.

**Comment by mapkyca** [comment]
Yes to the shim, otherwise this is going to be a breaking change for a lot of people.

Two comments thought:

1) I don't think this is particularly high priority for v1, I think it represents a fair amount of development and there are other things I'd like to see done first which are blocking v1.
2) Bootstrap has a pretty mature after market in third party templates - very handy when building sites on Known which you don't want to look like Known :D 

Given a choice I'd pick the bootstrap 4 upgrade over this, right now, and then roadmap grids further down the road.

**Comment by mapkyca** [comment]
I would suggest we do #2379 as part of this, as I believe it'd make it a bit easier to switch things about and gives folk the option to use different frameworks easier.

**Comment by mapkyca** [comment]
Additionally #1846

**Comment by johanbove** [comment]
As a benchmark I've uploaded [the latest Lighthouse report for my site](https://johanbove.info/lighthouse/social.johanbove.info_2019-09-25_22-30-08.report.html) running on Known v0.14.1 (Mapkyca build)
The "performance" score is currently 75.

**Comment by johanbove** [comment]
What do you think of moving the "themes" and the main template layout and styling to a CSS design system like https://tailwindcss.com/docs/utility-first ?

**Comment by jeremycherfas** [comment]
Having just started learning Tailwind, I would be all in favour. :) But that's just me.

**Comment by mapkyca** [comment]
No strong preference one way or another except to say that

1) I'd like to break view away from controller (as previously discussed)
2) This is definitely a post 1.0.0 thing (although not massively post 1.0.0). That being said a view/controller split could very well mean a breaking change, meaning a major number increase, however I'm not overly bothered by that at this stage.

**Comment by mapkyca** [comment]
Closing in favour of #2617
