### ISSUE TITLE
Replace obsolete bootstrap-toggle library

### ISSUE THREAD

**Issue by lindner** [idno/known#2439]
**Is your feature request related to a problem? Please describe.**

When attempting to upgrade to newer bootstrap I found that plugins are not supported.

Specifically https://github.com/minhur/bootstrap-toggle/issues/176 mentions this.

**Describe the solution you'd like**

It appears that an actively managed package is Bootstrap Switch:

https://github.com/Bttstrp/bootstrap-switch

It works with all versions of Bootstrap and would likely work well.

**Describe alternatives you've considered**

https://github.com/minhur/bootstrap-toggle/issues/186 documents a mechanism to work with boostrap 4, but it appears to have issues.

There may be a non-bootstrap version, but I have not investigated it yet.  (For example if we want to use css grid instead of bootstrap...)

**Comment by mapkyca** [comment]
I think @benwerd was keen to ditch bootstrap in favour of css grid.

If we're going to embark on a massive rewrite I'd actually like to explore using twig instead of the own rolled templating system. I think it's possible that we could run them concurrently so it wouldn't be an all or nothing proposition.

**Comment by mapkyca** [comment]
Closing as I believe this was handled by a previous patch
