### ISSUE TITLE
Tags database field empty for non-ASCII posts

### ISSUE THREAD

**Issue by nekr0z** [idno/known#2500]
## While trying to do this:
Look at `tags` database field for various entities.

## I encountered this error:
They contain nothing for entities with non-ASCII characters.

## Some other notes:
Tags themselves are shown correctly on site, and seem to be processed. However, in database the corresponding field is empty.

Give us some context: 

Current master, MySQL.

**Comment by mapkyca** [comment]
In general, I don't think this is a bug, because it depends on how they're passed. From the interface, #hastags don't end up in the database, they're searched for on the fly.

However, if you're explicitly passing tags fields as a variable, then these will be stored. 

This was the historic way of doing things, and was disabled through the UI in favour of on the fly tags, but still functionally exist and are used by various Micropub clients.

So, the question is this: are explicit tags in Cyrillic failing - I.e. you're using a Micropub client and the tags aren't being stored, or are you using hashtags in the post and these don't end up in the database as explicit tags?

**Comment by nekr0z** [comment]
> or are you using hashtags in the post and these don't end up in the database as explicit tags?

this one

**Comment by mapkyca** [comment]
This is expected behaviour, but I'm aware it's confusing.

These days I'm more of the view that search operations shouldn't be done at the database, so hashtags processed as a free text but powered by elastic search are probably the way to go.
