### ISSUE TITLE
Twitter plugin not working

### ISSUE THREAD

**Issue by jevdemon** [idno/known#2545]
## Some other notes: I also tried to install the separate Twitter plugin I saw here on GitHub.  This fixed the site crashing but I am still unable to enable the Twitter plugin (enable button won't turn blue, missing Twitter button when I post a status or blog entry).

Give us some context: 

* It'd also be really handy if you could tell us the contents of your ```version.known``` file
version = '1.0.0-rc.2'
build = 2019100601
* What database are you using? (e.g. mongo, mysql, postgres)
10.2.27-MariaDB - MariaDB Server per phpMyAdmin
* Any warnings or errors in your admin/diagnostics page?
You appear to be running directly from a git checkout. While this is fine, you might find a pre-packaged version of Known more stable.
* If this is a programming bug, can you include examples of any Micropub / API calls / webhook pings you make? Otherwise please don't worry about what this means!
* Bonus points - are you able to illustrate the issue with a unit test? If so, submit it as a pull request!

**Comment by mapkyca** [comment]
The crash is almost certainly due to using an old version of the twitter plugin (although I won't be able to say without seeing the logs).

If you're using the latest Known, an easy way to install the twitter plugin is to `composer require idno/twitter`, but assuming you've managed that before you can enable twitter you need to create a Twitter app and enter the oauth keys in the admin settings after activating.
