### ISSUE TITLE
Poor composer support for dependency bower-asset/mention 

### ISSUE THREAD

**Issue by lindner** [idno/known#2572]
## While trying to do this:

Run `composer install -vvv` in a dockerfile

## I encountered this error:

Composer tries to use git@github.com to clone dev-master, but that will not work if you have not setup a github ssh key.  Errors will manifest as below:

```
  - Installing bower-asset/mention (dev-master 1b588ef): Executing command (CWD): git --version

    Cloning to cache at '/root/.composer/cache/vcs/git-github.com-jakiestfu-Mention.js.git/'
Executing command (CWD): git clone --mirror 'git@github.com:jakiestfu/Mention.js.git' '/root/.composer/cache/vcs/git-github.com-jakiestfu-Mention.js.git/'
Executing command (CWD): git config github.accesstoken
Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos
Executing command (CWD): hostname
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+d5f398bc829a+2019-11-03+0834
to retrieve a token. It will be stored in "/root/.composer/auth.json" for future use by Composer.
Token (hidden):
```

## Some other notes:

You can workaround by using `composer install --prefer-dist` but most people won't do that.

Some options:
- Fork/publish the mention.js library
- Add some hacks to composer.json to prefer dist for bower-asset/mention
- Replace bower-asset/mention with something new?

**Comment by mapkyca** [comment]
Hmm.... well, especially since 1.0 is out, we should really change the docker image to be using the official packages, not doing a composer checkout (didn't think it was, but nvm).

I'd actually like to see the mention library replaced with something else, since there haven't been any code changes since 2015 so it's essentially abandoned. Ditto with toro tbh (which I'd like to see replaced with symfony), but that's a bigger job.
