### ISSUE TITLE
Allow syndication of comments

### ISSUE THREAD

**Issue by timmmmyboy** [idno/known#326]
Currently using http://brid.gy to grab interactions from silos and it would be nice to be able to reply directly in the comment area of a post and have that comment syndicate back to the silo. Bonus points if there were a way for the system to know what the original syndication method was and have this happen automatically.
##

**Comment by benwerd** [comment]
Bumping this again. Comment syndication would be really cool.

**Comment by mapkyca** [comment]
Going to close. I'm not sure if this is possible - certainly it's no longer possible with Facebook, since the recent API changes.

Mechanisms to support this may be possible - Known supports both webhooks and feeds on comments, so this may be something a third party plugin could do. 

Happy to make tweaks to facilitate this with e.g. bridgy.
