### ISSUE TITLE
Changing domain

### ISSUE THREAD

**Issue by hugoroy** [idno/Known#658]
I have changed the domain of my known instance in settings.

Now, it seems that pictures I uploaded under the previous domains are still using the old domain instead of the new. Hence display of pictures can easily break (if the former domain isn't pointing to the same thing any more, or because it does not have the same certificate for SSL/TLs, etc.)

I'm using mongodb.

Example: https://hugoroy.eu/2014/demoing-known-withknown-at-mozillaparis

**Comment by Phyks** [comment]
Not directly the same issue, but closely related:
I want to serve my Known on two different domains. I want it to be accessible on phyks.me and known.phyks.me, as the later was used for testing purpose, and I am not using it in "production" for my blog. I do not want to have dead links around, so I'd like to serve it from both URLs.

However, if I just make phyks.me point to the Known folder, no files can be loaded (but everything seems to work fine). I think this is because the rewrite rules is loading files from `Uploads/phyks.me` which does not exists as my uploads were made on known.phyks.me and are in `Uploads/known.phyks.me`.

I found a dirty (hacky) solution in issue #724: adding a `url = "http://known.phyks.me"` in my `config.ini` file seems to be enough.

**Comment by nekr0z** [comment]
This one seems to be half-killing syndication for me after moving a withknown instance to my own domain. Every post with pictures (even new ones) is having certificate issues. Could there be any fix at least for the hosted version? This one kills half the value of a Pro account.

**Comment by benwerd** [comment]
We're checking this out right now. Could you send me your Pro site address? ben@withknown.com

**Comment by nekr0z** [comment]
@benwerd I just did. I can attach a Bridgy log of failure, in case you're interested.

**Comment by nekr0z** [comment]
An update: I did some more testing, and it appears the wrong cert problem affects all publications for me, not just the ones with pictures. Even trying to curl any post results in failed handshake because of wrong certificate. So in effect, moving to another domain screwed webmentions completely and totally, at least in my case.

BTW, IndieAuth fails too, and wrong cert might be the reason of that as well.

**Comment by nekr0z** [comment]
Another update: actually, trying to even open the homepage in Chrome visitors get warning about insecure site. NET::ERR_CERT_COMMON_NAME_INVALID
So actually after moving site to another domain all the things https get royally broken.

**Comment by mapkyca** [comment]
Close in favour of #644 ?
