### ISSUE TITLE
Relative dates should not be relative too far away in the past

### ISSUE THREAD

**Issue by Phyks** [idno/Known#662]
Hi,

I just imported some of my old articles in my Known instance and got things like "Phyks published this one year ago".

I think that maybe relative dates should not be relative too far in the past, to keep some granularity in time. Many "silos" use relative dates up to a month at most, I think.

**Comment by benwerd** [comment]
Agree: I think this is a good approach. Timezones are an issue, and we've used relative dates as a way to avoid that kind of confusion - but, eg, "17 weeks ago" is kind of meaningless. Will fix.

**Comment by Phyks** [comment]
Thanks a lot !

**Comment by mck182** [comment]
This was one of the things that also bothered me a bit, so I fixed it in mck182@2e1cd4fc5162a2946205f5794f6fd4d705fefb82

The timeago script claims it can handle timezone support just fine as long as the ISO date also has the timezone component (which it does in this case). Seems to work fine :)

I also omitted the time with the older posts, I personally don't find it too useful to have time at older posts but should be easy to tweak if you think otherwise.

I can do proper pull request if you think this is good (can also fix the time if you wish).
