### ISSUE TITLE
Support for oembed

### ISSUE THREAD

**Issue by squiddle** [idno/Known#737]
embedding links could be improved by using the oembed standard to support unknown services as well. currently all embedding is hardcoded in the default template.
Supporting this open API could be more future proof http://oembed.com/

Optionally the simplified API from embedly could be used http://embed.ly/

**Comment by benwerd** [comment]
Yes. This would be a good idea - and we should really support oembed in both directions! Embeddable posts would be a fun thing.

**Comment by mapkyca** [comment]
This might be of use: https://www.marcus-povey.co.uk/2014/03/06/embeddable-posts-in-idno/ 

Which also exports an oembed endpoint.

Having Known parse third party oembed endpoints is probably a bad idea - recommended practice is to only do that for whitelisted domains, since oembed raw is basically code injection.

That said, I'd say it might be handy to have a library function to make it easier, so that plugins (e.g. the soundcloud embed plugin (https://www.marcus-povey.co.uk/2014/08/14/soundcloud-embed-for-idno/) don't have to do the parsing themselves.

**Comment by mapkyca** [comment]
Can close..?

Known oembed export is provided by plugin, using arbitrary third party oembed without a whitelist or similar is a massive XSS vuln so is unlikely to be implemented.
