### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#741]
Somewhere along the line icon classes for some things have been removed - e.g. icon-time and icon-cogs.

**Comment by mapkyca** [comment]
Also icon-remove-circle

**Comment by mapkyca** [comment]
Also icon-share-alt

**Comment by mapkyca** [comment]
Ahh ... you've switched away to a custom fontello font.

**Comment by mapkyca** [comment]
Actually, this change breaks quite a lot of themes/syndication plugins. 

You should at least include all font-awesome fonts, ideally with bootstrap2 naming compatibility

**Comment by mapkyca** [comment]
icon-signin

**Comment by mapkyca** [comment]
It looks like you're also including fontawesome in the external... so perhaps there's a namespace collision here? Perhaps use known-icon-* for known extensions and let fontawesome handle icon-*?

**Comment by benwerd** [comment]
+1 to this. Sorry for the breakage. Will fix!

**Comment by benwerd** [comment]
A longer reply: giving plugin authors proper leeway to build on top of Known is key. Just including the resources that are useful to us as core developers is not what we should be doing. We'll make sure we leave plenty of tools for everyone in the future.

**Comment by erinjo** [comment]
All of the Font Awesome icons are in the Fontello package along with extras from other fonts to fill in the gaps. The difference is that the icon names might be different now. It's using the latest Font Awesome version, not the old version we were using. Some of the names have also been adjust to get past AdBlocker. The old Font Awesome files are still there, but Font Awesome actually shouldn't be referenced along with the fontello font because it was showing duplicate icons in some cases. If you spot missing icons in themes, let us know specifics.  We tried to get most of them updated, but the way themes over-right core, we might have missed a few.

**Comment by mapkyca** [comment]
Ahh.... good to know. Will change the names over.

If font-awesome is included in its entirety, it may not be necessary to namespace it off... I can see good and bad for both...

**Comment by mapkyca** [comment]
Seems to be resolved, so closing. Still need the fontello config.json to be added by whoever has it in their working directory though...
