### ISSUE TITLE
Request: a Chrome extension

### ISSUE THREAD

**Issue by cmshawns** [idno/Known#797]
Like the add-on available for Firefox. It appears [one has already been created](https://github.com/mapkyca/KnownChrome), but it needs to be installed on the server. (I'm currently using the hosted stream.)

**Comment by benwerd** [comment]
We're in the process of creating a gateway on withknown.com to make this
easier. That way you'll just be able to find the extension in the Chrome
store. We're doing something similar for Firefox, so that we can better
work with their marketplace.


On Tue, Mar 17, 2015 at 11:42 AM, Shawn S. <notifications@github.com> wrote:

> Like the add-on available for Firefox. It appears one has already been
> created <https://github.com/mapkyca/KnownChrome>, but it needs to be
> installed on the server. (I'm currently using the hosted stream.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/797>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by cmshawns** [comment]
Sounds like a good plan. Thanks :-)
