### ISSUE TITLE
Bridgy connect UX

### ISSUE THREAD

**Issue by beck24** [idno/Known#843]
Just connected Bridgy to both twitter and facebook.  When you return to the Bridgy page after authorizing the app there's no message or anything indicating it was successful and the page looks the same with call-to-action buttons for activating the services you've just activated.

I checked on Twitter and FB and the Bridgy app is authorized.  It would be better if it would tell you that it's already connected.

![screen shot 2015-04-02 at 10 52 36 am](https://cloud.githubusercontent.com/assets/738363/6973659/134bc3aa-d941-11e4-8f4d-5ca75cc512d3.png)

**Comment by erinjo** [comment]
Completely agree. We've talked a lot about this. There actually isn't anything passed back to us from Bridgy, so we don't have a way to tell if people are authenticated or not. In a perfect world, we would also know if they were no longer authenticated with Bridgy, since they could also remove their connection from the Bridgy website. We've been discussing possible hacks and ways that we could capture some of this information, with the short term goal of making it feel similar to authenticating with other social networks and the long term goal of just building it in completely so that the user never has to authenticate through Bridgy.

**Comment by beck24** [comment]
Fair enough, that does certainly make it difficult.  I'll just leave this ticket here as a reminder then in case someone comes up with a good solution.

**Comment by andtheWings** [comment]
+1 Yeah, I found this pretty confusing although I understand the limitations you're facing.

**Comment by kylewm** [comment]
What is needed on the Bridgy side to support this? More information when Bridgy redirects back to Known, or a query endpoint that you can use to check the status of an account every time they open this page?

**Comment by benwerd** [comment]
A query endpoint would probably be the least brittle. But it also depends
on what's easy from your side?

On Tue, Apr 28, 2015 at 10:50 AM, Kyle Mahan <notifications@github.com>
wrote:

> What is needed on the Bridgy side to support this? More information when
> Bridgy redirects back to Known, or a query endpoint that you can use to
> check the status of an account every time they open this page?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/843#issuecomment-97151871>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by kylewm** [comment]
I think both would be pretty easy, I'll work on an endpoint and let you know!

**Comment by benwerd** [comment]
Awesome! Let me know if I can help in any way.

On Tue, Apr 28, 2015 at 11:25 AM, Kyle Mahan <notifications@github.com>
wrote:

> I think both would be pretty easy, I'll work on an endpoint and let you
> know!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/843#issuecomment-97162527>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by kylewm** [comment]
I started working on this here https://github.com/kylewm/Known/tree/bridgy-connected; so that it shows the button as "connected" (gray background) after the user connects. Have two follow up questions:

1. I want to send out a couple requests to fetch the user pages and update their "connected" status in the future. Would you rather do these synchronously on page load or an AJAXy thing so that it loads the initial page quickly?

2. Do you want users to be able to disable their Bridgy account through the Known dashboard? I'm guessing yes. I realized Bridgy's still not giving us quite enough information to do that but it's easy to add.

![bridgy-facebook-connected](https://cloud.githubusercontent.com/assets/950127/7475875/0aefd46c-f2ff-11e4-8098-845adf8e19ce.png)

**Comment by benwerd** [comment]
You are amazing. Thank you thank you thank you.

I'm of two minds about the page request. Mostly I think it depends on how responsive the brid.gy endpoint is; if it's fast, might as well load it synchronously.

So far I've seen one request for a brid.gy disconnect option. I told them to go directly to brid.gy to do that.

**Comment by davidmead** [comment]
saw that last night after the updates. One question I have is this; what
if you're already connected to brid.gy? Can we show that?

On Tue, May 5, 2015 at 2:01 PM, Ben Werdmuller <notifications@github.com>
wrote:

> You are amazing. Thank you thank you thank you.
>
> I'm of two minds about the page request. Mostly I think it depends on how
> responsive the brid.gy endpoint is; if it's fast, might as well load it
> synchronously.
>
> So far I've seen one request for a brid.gy disconnect option. I told them
> to go directly to brid.gy to do that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/843#issuecomment-99159590>.
>



-- 
David Mead

http://twitter.com/davidmead
http://davidjohnmead.com
http://dmwebsites.com

**Comment by kylewm** [comment]
@davidmead that is a good question. It will not show it right away because it has no way to know the Twitter/Facebook username that you connected to Bridgy with. If you click the button again, it will reauth with Bridgy, and then it will show up as connected from then on...

**Comment by kylewm** [comment]
@benwerd I need some input :)

I'm working on an AJAX call that fetches the bridgy user page, checks for microformats that indicate whether the account has been enabled/disabled since the last time we checked, and updates the user info in the DB if so.

I'm at the point where I need to decide about how to notify the user that the account status has changed. I can either: 

1. low-tech: send back simply `{changed: true}` and have the /account/bridgy/ page forcibly refresh itself with `window.location.reload(true);`
2. high-tech: render the /account/bridgy/ page programmatically and send its HTML back as part of the JSON payload; then in the browser, use JS to swap out the old signup form with the new signup form.

I've pretty much coded it both ways already, so neither one is more difficult than the other. But 2 is of course a little more complex and a little more code. Do you have a preference?

**Comment by benwerd** [comment]
@kylewm This is awesome.

I prefer option 2 - as long as the rendering is done on the Known site. So Bridgy sends back {changed: true} and Known re-renders the page on the fly in JS.

Does that make sense / is that in line with what you were thinking?

**Comment by kylewm** [comment]
Yes absolutely. The ajax call is actually to Known itself (I added another endpoint at /account/bridgy/check), so it can re-render the page as part of that check. 

The one bit I was confused about -- should I use `\Idno\Core\Webservice::get()` to get the rendered page as I have done [in the commented out bit here](https://github.com/idno/Known/compare/master...kylewm:bridgy-update#diff-a25fb73fe5bd8c4289ad27dc5d2f776eR27), or is there a better way to fetch and render a Page to string internally?

**Comment by benwerd** [comment]
This has been fixed awesomely by @kylewm.
