### ISSUE TITLE
Uploading images for posts is impossible on mobile

### ISSUE THREAD

**Issue by nekr0z** [idno/known#889]
Insert/edit image part on screenshot below can not be scrolled, so this function is not accessible on mobile.

![screenshot_2015-05-10-19-11-29](https://cloud.githubusercontent.com/assets/1515080/7555338/44510b30-f751-11e4-9549-eab5af322c42.png)
##

**Comment by benwerd** [comment]
Thanks for highlighting this. We'll find a better way to add images on mobile devices.

**Comment by chrisaldrich** [comment]
Is there a way to use a similar workflow that occurs when doing a native "photo post" rather than the alternate flow here that happens when clicking on the photo icon within the tinymce-esque toolbar? Doing something like this as a temporary mobile fix may be easy enough, and those who are looking to add the description, height, width could at least use raw html/css tweaks in the source code... (though I'll also mention that the source code icon pops up a fixed width window that also doesn't give access to it's full functionality either.)

**Comment by mapkyca** [comment]
Someone might want to try with #1941 and the new mobile theme

**Comment by mapkyca** [comment]
Is this still an issue now we're on TinyMCE 5? (reopen if so)
