### ISSUE TITLE
Vagrant and Ansible configuration files breaks Known instances running Nginx and/or MariaDB

### ISSUE THREAD

**Issue by herbsmn** [idno/Known#891]
When I installed the Known 0.7.8 and restarted my server Known stopped working. I noticed that Nginx and MariaDB weren't included in the Ansible folder so I am wondering if that is the problem. The other issue is that I can't delete the Ansible folder and other folders because it seems like something got mounted as a read-only file. I don't know what is mounting, if anything, but if I knew what was being mounted, I figure I could then remount it as a read/write mount which would then let me delete the ansible folder.

**Comment by kylewm** [comment]
I believe @jamesduffy contributed the ansible/docker stuff, any ideas?

**Comment by jamesduffy** [comment]
@kylewm Thanks for mentioning me otherwise I would have never seen this. 

Ansible and vagrant should be totally independent from your existing installation.

MariaDB and Nginx are not included because I created the ansible provisioning scripts to match the installation instructions in the docs. 

But even without them being included you can run your server any way you like. Vagrant and ansible are used to create a development environment and run a virtual machine. 

@herbsmn The issues would not be related to my commit unless you are running Known inside of vagrant.

**Comment by benwerd** [comment]
Closing this; as @jamesduffy says, ansible and vagrant shouldn't interfere with nginx.

**Comment by herbsmn** [comment]
Sorry for my misunderstanding when creating this issue. Just as a follow-up, I figured out all of the configurations and got my site working again. I'll try to dig deeper next time before making frivolous issues. Thanks for the responses. Sometimes it helps to know what the problem isn't so that resources can be devoted to looking elsewhere.

**Comment by benwerd** [comment]
Actually, thank you for posting this: it turned out that the configuration files were interfering with other software (eg Elastic Beanstalk, which we use for withknown.com), so we renamed them to emphasize they were "sample" configurations.

**Comment by herbsmn** [comment]
ah, well I'm glad that I inadvertently helped the cause. :-)

**Comment by jamesensembleads** [comment]
Now if only I could get @benward to come over to my office and help me deploy a docker to AWS EB... ;)

I hope everyone finds vagrant in known useful as well. It has helped me get things setup and playing around with them.
