### ISSUE TITLE
Bridgy connection not working for Facebook Pages from within Known CMS

### ISSUE THREAD

**Issue by MatthieuScarset** [idno/Known#905]
Hi, 

I've just realized Facebook Pages are not listed if I try to connect to Bridgy from the interaction control panel within Known.

However, it is working when i connect directly from the Bridgy official website.

Any idea why and how to solve it ?

**Comment by physcocode** [comment]
Yea me too have encountered this , but this seems a problem within bridgy and not known cc @snafered @benwerd

**Comment by kylewm** [comment]
I helped with the Bridgy/Known integration, so hopefully can help troubleshoot this.

I recorded a video of what it looks like when I auth with Bridgy+Facebook through the Known dashboard -- https://kylewm.com/test/known-bridgy-facebook-pages.webm -- it does prompt me to select a page after I've authorized.

When you do the same thing, it redirects you right back to Known without prompting for a page?

Unfortunately since I am a "developer" on the Bridgy Facebook app, they don't give me nearly as much hassle about permissions and such, so it can be hard to anticipate these issues

**Comment by physcocode** [comment]
@kylewm if i give you login credintial of my facebook can you test it ?

**Comment by kylewm** [comment]
Thanks for the offer @physcocode, I don't think that will be necessary. I should be able to test with a FB Test User (but probably not until this evening)

**Comment by physcocode** [comment]
@kylewm i probably just forgot about that *sigh* while you test i probably will be having a good night sleep here in india.

PS : I know it is completly unrelated to issue :p

**Comment by kylewm** [comment]
I currently suspect the issue is that you cannot *disable* the Facebook+Bridgy connection to a Facebook Page. The call to Bridgy to disable the account associated with the FB Page reports failure.

**Comment by kylewm** [comment]
For reference, I'm tracking that issue here https://github.com/snarfed/bridgy/issues/409

**Comment by kylewm** [comment]
@MatthieuScarset @physcocode could you try it again and see if it works now? I'm able to toggle the connection to FB pages on and off now.

**Comment by physcocode** [comment]
Bravo! Its working fine now !
![untitled](https://cloud.githubusercontent.com/assets/7591484/7788510/b7ecbba2-025a-11e5-85e2-549ea6b0521b.png)

**Comment by physcocode** [comment]
This have been fixed !
