### ISSUE TITLE
Chicken and egg on registration of hooks

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#918]
This may be an edgecase, but it is not possible to have a login success/fail event triggered to guard APILogin via a plugin, because plugins aren't booted at this point.

But, I believe there was a prior issue which meant that API users needed to be logged in before their events were registered.

Perhaps there's a case for a pre-boot event...?

**Comment by mapkyca** [comment]
Bumping this, this is far from an edge case.

Not having event hooks registered basically prevents third party authentication plugins like mapkyca/KnownOAuth2 from functioning. 

(Discovered while debugging mapkyca/KnownKnown#1, linked for reference)

**Comment by kylewm** [comment]
I think this is closely related to a problem with IndiePub too. By the time it handles the request and decides the user's indieauth token is valid and logs them in, everybody else has already set themselves up in the "logged out" state.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/918#issuecomment-168234951" class="u-in-reply-to"></a>I fixed it for the api by triggering the API login code after the instantiation of Plugins(). I suspect it might just be that we need to re-run the session boot at the end of the Plugin boot.

Little bit of a fudge, but might work for this too...

**Comment by kylewm** [comment]
Any chance that means that plugins can register a hook on 'user/auth' and that hook will be invoked before every authed request? Specifically, I would like to do [this block](https://github.com/idno/Twitter/blob/master/Main.php#L35) in response to authorization instead of during init.

Or is your change more specific to API usage?

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/918#issuecomment-168238530" class="u-in-reply-to"></a>My patch fixes it for API only I'm afraid (it was the lowest impact change as I didn't have much time to test everything), however something similar could be adopted - reset the session user as a result of an auth trigger after plugin boot...

**Comment by kylewm** [comment]
Thanks that makes sense! OK, will need to give it some more thought.

**Comment by benwerd** [comment]
I'd hoped to get out a release today, but I'm in urgent care instead
(booooo). Which means we have time to get in a fix for this before the 0.9
release. It would be really nice to get this properly working.

Rearranging the auth code to run after a boot event seems very reasonable.

On Thursday, December 31, 2015, Kyle Mahan <notifications@github.com> wrote:

> Thanks that makes sense! OK, will need to give it some more thought.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/918#issuecomment-168241084>.
>


-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by kylewm** [comment]
@benwerd that's no fun, hope you feel better soon!

Typing this out mostly for my own understanding. Right now, a request handler kicks off like this:

1. Site and session are created
1. calls `Session::APIlogin`
  1. APIlogin attempts to authorize via API key. 
  1. If that fails, delegates by firing hook "user/auth/api" (but no hooks are registered because there are no plugins yet)
1. `Session::refreshCurrentSessionuser`
  1. attempts to authorize via credentials stored in the session. Doesn't fire any hooks.
1. All plugins start up and register their hooks
1. (mapkyca proposes moving call to `APIlogin` here, so that plugins are registered)

Right now "user/auth" and "user/auth/api" have confusingly similar names but do very different things. ("user/auth" is sent after-the-fact, is purely informative, and is not sent at all during startup).

I'd like to emphasize the distinction between "login" (when the user enters a username and password and clicks submit) and "auth" (when credentials are checked at the beginning of a request). I propose to use the hooks to "user/auth/request", "user/auth/success" and "user/auth/failure" for the latter, and combine the API auth with the regular user auth.

1. Site and session are created
1. All plugins start up and register their hooks
1. `Session::tryAuthUser` called at the beginning of each request
  1. fire hook "user/auth/request" which delegates authorization to plugins. if any plugin (right now, I think that's IndiePub or OAuth2) returns a $user, then we're done!
  1. if no user, try to authorize via the API key
  1. if no API user, then try to authenticate via user credentials in the session
1. if any of the above mechanisms succeeds, fire "user/auth/success"
  1. syndication plugins would listen for this event to call `registerServiceAccount`
1. if none succeed, fire "user/auth/failure".

Sound like a plan?

**Comment by mapkyca** [comment]
Closing this, as most of the problems have been resolved by #1125
